#!/bin/bash -eu

rootdir="$(readlink -f $(dirname $0)/../../../../)"
shl="/usr/share/bootnet/libs/shlib.shl"
if [ -f "$rootdir/shlib/$shl" ] ; then
. "$rootdir/shlib/$shl"
else
. "$shl"
fi

shlib_load "bootnet"

tap=$1

nic=$(find_a_bridge)

/usr/sbin/brctl addif $nic $tap
/sbin/ifconfig $tap 0.0.0.0 promisc up

/sbin/ip link set $tap up
